name: app/ deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'app/*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy docker-compose.yml
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script_stop: true
          # TODO: Autogenerate raw url
          script: |
            cd app
            curl https://raw.githubusercontent.com/DHSH-Softwareprojekt-WINF119/docker/main/app/docker-compose.yml > docker-compose.yml
