name: app/ deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'app/*'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3
          cache: 'pip'
      - name: Install docker-compose
        run: pip install --upgrade wheel docker-compose
      - name: Modify PATH
        run: export PATH="$PATH:$HOME/.local/bin"
      - name: Lint docker-compose.yml
        run: docker-compose -f app/docker-compose.yml config -q

  deploy:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Deploy docker-compose.yml
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script_stop: true
          # TODO: Autogenerate raw url
          script: |
            cd app
            curl https://raw.githubusercontent.com/DHSH-Softwareprojekt-WINF119/docker/main/app/docker-compose.yml > docker-compose.yml
